const LAST_GAME_DATA = ' LAST_GAME_DATA';
const USER_DATA='USER_DATA';
const GET_WALLET_DATA=' GET_WALLET_DATA';
const GET_LANDING_DATA=' GET_LANDING_DATA';
const GET_PRODUCTS_LIST=' GET_PRODUCTS_LIST';
const UPDATE_BELL = "UPDATE_BELL";
const GET_LIVE_PLANS = "GET_LIVE_PLANS";
const BUY_LIVE_PLAN = "BUY_LIVE_PLAN";
const GET_FANJOY_DATA = "GET_FANJOY_DATA";
const CREATOR_ID = "CREATOR_ID";
const GALLERY_DATA = "GALLERY_DATA";
const CREATOR_PAGE_DATA = "CREATOR_PAGE_DATA";
const WIN_EXPERIENCE_PRODUCT_DATA = "WIN_EXPERIENCE_PRODUCT_DATA";
const EXPERIENCE_PRODUCT_DETAILS = "EXPERIENCE_PRODUCT_DETAILS";
const EXPERIENCE_ID = "EXPERIENCE_ID";
const EXPERIENCE_DETAILS = "EXPERIENCE_DETAILS";
const GAME_SHOW_WINNERS = "GAME_SHOW_WINNERS";
const LUCKY_DRAW_WINNERS = "LUCKY_DRAW_WINNERS";
const LEADER_BOARD_WINNERS = "LEADER_BOARD_WINNERS";
const DEALS_JOY = "DEALS_JOY";
const TRIVIA_JOY = "TRIVIA_JOY";
const GAME_ENTER_STATUS = "GAME_ENTER_STATUS";
const TOTAL_LIVES = "TOTAL_LIVES";
const types = {
  LAST_GAME_DATA,
  USER_DATA,
  GET_WALLET_DATA,
  GET_LANDING_DATA,
  GET_PRODUCTS_LIST,
  UPDATE_BELL,
  GET_LIVE_PLANS,
  GET_FANJOY_DATA,
  CREATOR_ID,
  GALLERY_DATA,
  CREATOR_PAGE_DATA,
  WIN_EXPERIENCE_PRODUCT_DATA,
  EXPERIENCE_PRODUCT_DETAILS,
  EXPERIENCE_ID,
  EXPERIENCE_DETAILS,
  GAME_SHOW_WINNERS,
  LUCKY_DRAW_WINNERS,
  LEADER_BOARD_WINNERS,
  DEALS_JOY,
  TRIVIA_JOY,
  GAME_ENTER_STATUS,
  TOTAL_LIVES
};

export default types;