const LAST_GAME_DATA = ' LAST_GAME_DATA';
const USER_DATA='USER_DATA';
const GET_WALLET_DATA=' GET_WALLET_DATA';
const GET_LANDING_DATA=' GET_LANDING_DATA';
const GET_PRODUCTS_LIST=' GET_PRODUCTS_LIST';
const UPDATE_BELL = "UPDATE_BELL";
const GET_LIVE_PLANS = "GET_LIVE_PLANS";
const BUY_LIVE_PLAN = "BUY_LIVE_PLAN";
const GET_FANJOY_DATA = "GET_FANJOY_DATA";
const CREATOR_ID = "CREATOR_ID";
const GALLERY_DATA = "GALLERY_DATA";
const CREATOR_PAGE_DATA = "CREATOR_PAGE_DATA";
const WIN_EXPERIENCE_PRODUCT_DATA = "WIN_EXPERIENCE_PRODUCT_DATA";
const EXPERIENCE_PRODUCT_DETAILS = "EXPERIENCE_PRODUCT_DETAILS";
const types = {
  LAST_GAME_DATA,
  USER_DATA,
  GET_WALLET_DATA,
  GET_LANDING_DATA,
  GET_PRODUCTS_LIST,
  UPDATE_BELL,
  GET_LIVE_PLANS,
  GET_FANJOY_DATA,
  CREATOR_ID,
  GALLERY_DATA,
  CREATOR_PAGE_DATA,
  WIN_EXPERIENCE_PRODUCT_DATA,
  EXPERIENCE_PRODUCT_DETAILS
};

export default types;