const SHOW_LOADER = 'SHOW_LOADER';
const HIDE_LOADER = 'HIDE_LOADER';
const CART_COUNTER = 'CART_COUNTER';
const LAST_GAME_DATA = 'LAST_GAME_DATA';
const USER_DATA = 'USER_DATA';
const GET_WALLET_DATA = 'GET_WALLET_DATA';
const GET_LANDING_DATA = 'GET_LANDING_DATA';
const GET_PRODUCTS_LIST = 'GET_PRODUCTS_LIST';
const UPDATE_BELL = 'UPDATE_BELL';
const GET_LIVE_PLANS = 'GET_LIVE_PLANS';
const BUY_LIVE_PLAN = 'BUY_LIVE_PLAN';
const GET_FANJOY_DATA = 'GET_FANJOY_DATA';
const CREATOR_ID = 'CREATOR_ID';
const GALLERY_DATA = 'GALLERY_DATA';
const CREATOR_PAGE_DATA = 'CREATOR_PAGE_DATA';
const WIN_EXPERIENCE_PRODUCT_DATA = 'WIN_EXPERIENCE_PRODUCT_DATA';
const EXPERIENCE_PRODUCT_DETAILS = 'EXPERIENCE_PRODUCT_DETAILS';
const EXPERIENCE_ID = 'EXPERIENCE_ID';
const EXPERIENCE_DETAILS = 'EXPERIENCE_DETAILS';
const GAME_SHOW_WINNERS = 'GAME_SHOW_WINNERS';
const LUCKY_DRAW_WINNERS = 'LUCKY_DRAW_WINNERS';
const LEADER_BOARD_WINNERS = 'LEADER_BOARD_WINNERS';
const DEALS_JOY = 'DEALS_JOY';
const TRIVIA_JOY = 'TRIVIA_JOY';
const GAME_ENTER_STATUS = 'GAME_ENTER_STATUS';
const TOTAL_LIVES = 'TOTAL_LIVES';
const ALL_CREATORS_LIST = 'ALL_CREATORS_LIST';
const CAR_DATA = 'CART_DATA';
const FANJOY_ALL_DATA = 'FANJOY_ALL_DATA';
const REMOVE_CAR_DATA = 'REMOVE_CAR_DATA';
const PRODUCTS_DETAILS = 'PRODUCTS_DETAILS';
const CREATORS_EXPERIENCE_LIST = 'CREATORS_EXPERIENCE_LIST';
const IS_LOADING = 'IS_LOADING';
const BELL_NOTIFICATION = 'BELL_NOTIFICATION';
const FANJOY_DATA_LIST = 'FANJOY_DATA_LIST';
const POST_LIVELUCKY_DRAW = 'POST_LIVELUCKY_DRAW';
const SLUG_DETAILS = 'SLUG_DETAILS';
const types = {
  SHOW_LOADER,
  HIDE_LOADER,
  CART_COUNTER,
  POST_LIVELUCKY_DRAW,
  LAST_GAME_DATA,
  USER_DATA,
  GET_WALLET_DATA,
  GET_LANDING_DATA,
  GET_PRODUCTS_LIST,
  UPDATE_BELL,
  GET_LIVE_PLANS,
  GET_FANJOY_DATA,
  FANJOY_ALL_DATA,
  CREATOR_ID,
  GALLERY_DATA,
  CREATOR_PAGE_DATA,
  WIN_EXPERIENCE_PRODUCT_DATA,
  EXPERIENCE_PRODUCT_DETAILS,
  EXPERIENCE_ID,
  EXPERIENCE_DETAILS,
  GAME_SHOW_WINNERS,
  LUCKY_DRAW_WINNERS,
  LEADER_BOARD_WINNERS,
  DEALS_JOY,
  TRIVIA_JOY,
  GAME_ENTER_STATUS,
  TOTAL_LIVES,
  ALL_CREATORS_LIST,
  CAR_DATA,
  REMOVE_CAR_DATA,
  PRODUCTS_DETAILS,
  CREATORS_EXPERIENCE_LIST,
  IS_LOADING,
  BELL_NOTIFICATION,
  FANJOY_DATA_LIST,
  SLUG_DETAILS,
};

export default types;
